name: Node.js

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: current
        cache: 'yarn'

    - name: Run Task
      run: yarn && yarn update

    - name: Commit to Github
      uses: stefanzweifel/git-auto-commit-action@v5